### PR TITLE
BugFix: Strip definition path in AncestorsHaveProperties

### PR DESCRIPTION
**Pull request by pareshverma91**
Strip definition path when verifying that ancestors have properties.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@pareshverma91__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (paverma). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by fearthecowboy** [comment]
@pareshverma91  without feedback, I'm closing this - reopen if you still want this looked at.

**Comment by azurecla** [comment]
Hi __@pareshverma91__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (paverma). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by pareshverma91** [comment]
Hi, sorry for going awol on you.
The current version of autorest fails for a swagger specification
{
    "consumes": [
        "application/json"
    ],
    "definitions": {
        "aModel": {
            "properties": {
                "data": {
                    "type": "object"
                }
            }
        },
        "bModel": {
            "allOf": [
                {
                    "$ref": "#/definitions/aModel"
                }
            ]
        },
        "cModel": {
            "allOf": [
                {
                    "$ref": "#/definitions/bModel"
                }
            ]
        },
        "dModel": {
            "allOf": [
                {
                    "$ref": "#/definitions/cModel"
                }
            ]
        }
    },
    "info": {
        "description": "A summary of a a bug",
        "title": "Bug Example",
        "version": "01.00.00"
    },
    "paths": {
        "/a/path": {
            "get": {
                "description": "a path",
                "operationId": "getAPath",
                "responses": {
                    "200": {
                        "description": "A positive response",
                        "schema": {
                            "$ref": "#/definitions/aModel"
                        }
                    }
                }
            }
        }
    },
    "produces": [
        "application/json"
    ],
    "schemes": [
        "https"
    ],
    "swagger": "2.0"
}

with error
PS [11/14/2016 4:35 PM] C:\codebase\azure-repos\autorest\del> AutoRest.exe -CodeGenerator Azure.CSharp -Modeler Swagger -Input .\fails.json -Namespace Hello -OutpuDirectory "./hello" -verbose
Code generation failed.
AutoRest.exe -CodeGenerator Azure.CSharp -Modeler Swagger -Input .\fails.json -Namespace Hello -OutpuDirectory ./hello -verbose
INFO: AutoRest Core 0.17.0.0
INFO: Initializing modeler.
INFO: Successfully initialized modeler Swagger v 0.17.0.0.
INFO: Parsing swagger json file.
INFO: Generating client model from swagger model.
WARNING: ModelTypeIncomplete: This definition lacks the property 'description', which is required for model types
    Location: Path: #->Definitions->aModel
WARNING: ServiceDefinitionParameters: Parameters "subscriptionId" or "api-version" are referenced but not defined in the parameters section of Service Definition
    Location: Path: #->Parameters
FATAL: Error generating client model: The given key was not present in the dictionary.
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at AutoRest.Swagger.SwaggerModeler.AncestorsHaveProperties(Dictionary`2 properties, String extends)
   at AutoRest.Swagger.SwaggerModeler.BuildCompositeTypes()
   at AutoRest.Swagger.SwaggerModeler.Build(IEnumerable`1& messages)
   at AutoRest.Core.AutoRest.Generate(Settings settings)

However, if the schema is modified to the following, the generation succeeds:
{
    "consumes": [
        "application/json"
    ],
    "definitions": {
        "aModel": {
            "properties": {
                "data": {
                    "type": "object"
                }
            }
        },
        "bModel": {
            "allOf": [
                {
                    "$ref": "aModel"
                }
            ]
        },
        "cModel": {
            "allOf": [
                {
                    "$ref": "#/definitions/bModel"
                }
            ]
        },
        "dModel": {
            "allOf": [
                {
                    "$ref": "#/definitions/cModel"
                }
            ]
        }
    },
    "info": {
        "description": "A summary of a a bug",
        "title": "Bug Example",
        "version": "01.00.00"
    },
    "paths": {
        "/a/path": {
            "get": {
                "description": "a path",
                "operationId": "getAPath",
                "responses": {
                    "200": {
                        "description": "A positive response",
                        "schema": {
                            "$ref": "#/definitions/aModel"
                        }
                    }
                }
            }
        }
    },
    "produces": [
        "application/json"
    ],
    "schemes": [
        "https"
    ],
    "swagger": "2.0"
}

**Comment by fearthecowboy** [comment]
@olydis can you verify:
- that this doesn't have any side-effects
- and why the heck we needed this fix? This seems like we should have been failing long ago...

**Comment by olydis** [comment]
We should have been failing indeed, as far as I can tell the fix makes perfect sense. I'll commit a testcase.

Problem: `AncestorsHaveProperties` requires a model definition name, not a path to one - "all other calls" (namely one) provide that via `StripDefinitionPath`, only the *recursive call* within `AncestorsHaveProperties` does not - and no, we don't have a single test case that caught this (to get into this code path you indeed need an ancestor of an ancestor that does have any properties).

I'd actually suggest an alternative solution:
Strip the definition path within the function (i.e. input sanitation), as otherwise the next person calling this function will make the same mistake.

**Comment by fearthecowboy** [comment]
Yeah, the sanitation step sounds better.

**Comment by fearthecowboy** [comment]
@azuresdkci retest this please

**Comment by pareshverma91** [comment]
To fix the build issue, I had added another commit to lower the moment.d.ts version (a recent change in it uses typescript 2.0 features, which are not compatible with the version the tests use), but it seems Garett has resolved this issue in master by bumping up the typescript version. Hence, brought in master, and reverted my moment.d.ts change.

**Comment by pareshverma91** [comment]
@fearthecowboy bumping.

**Comment by fearthecowboy** [comment]
@azuresdkci retest this please

**Comment by fearthecowboy** [comment]
@azuresdkci retest this please

**Pull request merged**
