### PR TITLE
[Python] CloudError updates

### PR DESCRIPTION
**Pull request by annatisch**
Also updated doc strings to include exception info.

### CODE REVIEW

**Comment by annatisch** [comment]
@lmazuel  - let us know if/when this is good to go :)

**Comment by annatisch** [comment]
@fearthecowboy - This should be okay to merge now :)

**Comment by fearthecowboy** [comment]
Sweet @annatisch  - thanks!
You rock!

**Comment by lmazuel** [comment]
Fixes:
https://github.com/Azure/autorest/issues/1460
https://github.com/Azure/autorest/issues/1050

**Pull request merged**
