### PR TITLE
Converted required primitive parameters and properties to be non-nullable

### PR DESCRIPTION
**Pull request by stankovski**
Implements #492, ~~#513~~, and #375

### CODE REVIEW

**Comment by stankovski** [comment]
@brjohnstmsft can you take a look at this PR to make sure it addresses #492, #513, and #375?

**Comment by brjohnstmsft** [comment]
Looking...

**Comment by brjohnstmsft** [comment]
The PR is too big to leave inline comments, so I'll just comment here. In `CSharpCodeNamer.cs`:

```csharp
private IType NormalizeSequenceType(SequenceType sequenceType)
{
    sequenceType.ElementType = NormalizeTypeReference(sequenceType.ElementType);
    if (sequenceType.ElementType.IsValueType())
    {
        sequenceType.NameFormat = "IList<{0}?>";
    }
    else
    {
        sequenceType.NameFormat = "IList<{0}>";
    }
    return sequenceType;
}

private IType NormalizeDictionaryType(DictionaryType dictionaryType)
{
    dictionaryType.ValueType = NormalizeTypeReference(dictionaryType.ValueType);
    if (dictionaryType.ValueType.IsValueType())
    {
       dictionaryType.NameFormat = "IDictionary<string, {0}?>";
    }
    else
    {
        dictionaryType.NameFormat = "IDictionary<string, {0}>";
    }
    return dictionaryType;
}
```
Does this mean that collection elements will always be nullable, even if the collections themselves are required?

**Comment by brjohnstmsft** [comment]
In `AcceptanceTests.cs`:

```csharp
// NO LONGER VALID - Birthday is not nullable as such validation is removed
// var missingRequired =
//    Assert.Throws<ValidationException>(() => client.Polymorphism.PutValidMissingRequired(badRequest));
// Assert.Equal("Birthday", missingRequired.Target);
```

Why not just delete the commented-out code?

**Comment by brjohnstmsft** [comment]
Looks good overall. Some general comments:
- #492 looks resolved
- #375 looks resolved
- #513 does not appear to be addressed since it applies specifically to `readOnly` properties, not `required` properties. There is still an open question of how to model nullable versus non-nullable `readOnly` properties (Swagger currently has no way to express this without a vendor-specific extension).
- Do you plan to apply this change to Java as well? It has the same issues, only in Java's case it's about the usage of "boxed" primitives like `java.lang.Integer` instead of `int`, etc.

**Comment by stankovski** [comment]
@brjohnstmsft as far as nullability of collections, I didn't find anywhere in the swagger spec a way to say that the collection should not contain null values (http://swagger.io/specification/#itemsObject).

**Comment by stankovski** [comment]
@brjohnstmsft you are correct. I didn't read #513 in details. This particular change will leave readOnly fields as nullable since they are by definition not required. 
@jianghaolu I believe has `Integer` vs `int` implemented in java code already (not for readOnly but for required fields).

**Pull request merged**
