### PR TITLE
Null pointer fix for base64url & unixtime fix

### PR DESCRIPTION
**Pull request by jianghaolu**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@jianghaolu__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tbombach** [comment]
@jianghaolu I checked in a workaround for the Travis issue (it was unrelated to our codebase). Could you close and reopen this PR? I think that's the easiest way to merge master into your PR changes (just restarting the test build on Travis doesn't seem to work).

**Comment by jianghaolu** [comment]
Thanks @tbombach I just rebased my changes on top of master

**Comment by tbombach** [comment]
LGTM :+1:

**Pull request merged**
