### PR TITLE
Adding x-ms-error-response flag to schema

### PR DESCRIPTION
**Pull request by dsgouda**

### CODE REVIEW

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by dsgouda** [comment]
> test linux-x64

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by fearthecowboy** [comment]
> linux-x64 restart
> win32-x64 restart

**Comment by olydis** [comment]
> linux-x64 restart

**Comment by olydis** [comment]
> win32-x64 restart

**Pull request merged**
