### PR TITLE
GetDerivedType should consider only the derived types of the provided base type

### PR DESCRIPTION
**Pull request by dragonfly91**
Issue related to this PR: https://github.com/Azure/autorest/issues/1351

I've verified that this patch fixes the issue.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@dragonfly91__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (anudeeb). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by brjohnstmsft** [comment]
Please include test coverage.

**Comment by dragonfly91** [comment]
Added the test: PolymorphicDeserializationConsidersOnlyOwnDerivedTypes - please continue with review!

**Comment by tbombach** [comment]
@azuresdkci test this please!

**Pull request merged**
