### PR TITLE
Proposal to handle error status codes

### PR DESCRIPTION
**Pull request by dsgouda**
An alternative approach to handle exceptions 
@olydis @fearthecowboy PTAL

### CODE REVIEW

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by dsgouda** [comment]
hmm... I don't seem to have merge permissions here, @olydis a little help here...

**Comment by mikeblakeuk** [comment]
Any news on exception handling?

**Comment by fearthecowboy** [comment]
No; I've been completely swamped on other things. I don't have a timeline when I can get back to this at this point.

**Pull request merged**
