### PR TITLE
Updating package references for validator

### PR DESCRIPTION
**Pull request by dsgouda**
The packages have not been published yet, just a placeholder

### CODE REVIEW

**Comment by olydis** [comment]
This requires a bootstrapper improvement by Garrett, otherwise you have to bump the core's version in order for CI to pick it up

**Comment by dsgouda** [comment]
@olydis not sure I follow you

**Comment by olydis** [comment]
> linux-x64 restart

**Comment by olydis** [comment]
> win32-x64 restart

**Comment by olydis** [comment]
test

**Comment by olydis** [comment]
test

**Comment by olydis** [comment]
test

**Comment by olydis** [comment]
test

**Pull request merged**
