### PR TITLE
Feature: Anonymous security

### LINKED ISSUE #4135: Security should include "anonymous auth" along side key and token
In https://github.com/Azure/autorest.csharp/pull/1128 we are defining a "unauthed" case for some SDKs that want a anonymous auth by leaving it blank.

Maybe we should promote that to a named concept?

cc - @timbasham  @pakrym

### PR DESCRIPTION
**Pull request by timotheeguerin**
fix #4135

Added a new anonymous security option. This can be defined with an empty security entry in the openapi spec

```yaml
security: 
 -  {}
 - AADToken: [".default"]
```

Or via autorest config
```yaml
security: 
 - Anonymous
 - AADToken

Or cli flag
```bash
--security=['Anonymous', 'AADToken'] 
```

### CODE REVIEW

**Review by chamons — APPROVED** [review]

**Comment by mloskot** [comment]
When this is expected to be released?

I'm using the latest AutoRest (`cli version: 3.2.3; node: v12.19.1`) to generate a client for my API JSON document with either 
```json
  "security": [
    {}
  ],
```
or
```json
  "security": [
    {},
    {
      "HttpBasicAuth": []
    },
    {
      "HttpDigestAuth": []
    }
  ],
```
and it is failing for both, with error:
```
FATAL: Error: Invalid empty security requirement
```

**Comment by timotheeguerin** [comment]
Will probably be a little bit more time before it gets published to latest.

@mloskot you can use the @next versions to get this behavior right now.
```
--version:3.5.0-dev.1 --use:@autorest/modelerfour:4.20.0-dev.5
```
(See the readme for the latest values)

**Comment by mloskot** [comment]
@timotheeguerin Thanks for the tip. 

The autorest reference is fine, but the modelerfour one seem not:

```
>  autorest --preview --version:3.5.0-dev.1 --use:@autorest/modelerfour:4.20.0-dev.5
AutoRest code generation utility [cli version: 3.2.3; node: v12.19.1, max-memory: 2048 MB]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\mateuszl\.autorest\@autorest_core@3.5.0-dev.1\node_modules\@autorest\core\dist' (3.5.0-dev.1)
FATAL: Failed to install extension '@autorest/modelerfour:4.20.0-dev.5' (*)
  Error: Package '@autorest/modelerfour:4.20.0-dev.5' - '*' is not a valid package reference:
  Invalid package name "@autorest/modelerfour:4.20.0-dev.5": name can only contain URL-friendly characters
```

The `autorest --preview --version:3.5.0-dev.1 --help` does not mention the `--use` option and I've failed to web-search find anything on its value syntax.

**Comment by timotheeguerin** [comment]
sorry yeah its with `@` 
```
--use:@autorest/modelerfour@4.20.0-dev.5
```

Intresting we are lacking doc on this. I'll fix that.

**Comment by mloskot** [comment]
The `@` works, thank you, and for the docs update too.

**Pull request merged**
