### PR TITLE
Add 'head-as-boolean: true' default when 'azure-arm: true'

### LINKED ISSUE #3602: Auto set head-as-boolean if ARM mode is set
If `--azure-arm=True`, then autorest.core should pass `--head-as-boolean=True`

### PR DESCRIPTION
**Pull request by daviwil**
Fixes #3602.

/cc @ShivangiReja

### CODE REVIEW

**Review by lmazuel — APPROVED** [review]

**Review by ShivangiReja — APPROVED** [review]

**Comment by daviwil** [comment]
Closing/reopening to kick the CI pipeline.

**Comment by daviwil** [comment]
@iscai-msft is helping me look into the CI failure, seems that a [recent change](https://github.com/Azure/autorest.testserver/pull/226) to a spec in `testserver` has caused the Python generator output to change;

**Comment by iscai-msft** [comment]
@daviwil merged the fix to this on the python side

**Comment by daviwil** [comment]
Thanks a bunch @iscai-msft!

**Comment by daviwil** [comment]
Thanks for publishing the fix @iscai-msft, CI is green now :)

**Comment by daviwil** [comment]
@ShivangiReja This is now out in @autorest/core@3.0.6326, you can use `autorest --reset` and you should get the new version.

**Pull request merged**
