### PR TITLE
Fix exception in Log4NetTracingInterceptor default constructor

### LINKED ISSUE #1233: Log4NetTracingInterceptor default constructor throws FileNotFoundException
It is not possible to instantiate Log4NetTracingInterceptor without configuration file.
Default constructor passes null to this one:
https://github.com/Azure/autorest/blob/master/src/client/Microsoft.Rest.ClientRuntime.Log4Net/Log4NetTracingInterceptor.cs#L24

### PR DESCRIPTION
**Pull request by older**
Fixes  #1233

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@older__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by tbombach** [comment]
@azuresdkci test this please!

**Comment by fearthecowboy** [comment]
@azuresdkci retest this please

**Comment by tbombach** [comment]
Hi @older. This change looks good to me, and we'll merge it soon. Have you signed the CLA agreement before? I ask, since we've had trouble with our bot being able to get the status for who's signed the agreement before.

**Comment by azurecla** [comment]
__@older__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Pull request merged**
