### PR TITLE
optional enums with 1 value and x-ms-enum has modelAsString=false will be enum

### PR DESCRIPTION
**Pull request by amarzavery**
- required enum with 1 value will be treated as a constant (x-ms-enum extension is ignored)
- optional enum with 1 value and x-ms-enum has modelAsString=false will be treated as an enum
- optional enum with 1 value and x-ms-enum has modelAsString=true will be not be treated as an Enum
- optional enum with 1 value and no x-ms-enum extension will be treated as the same type that is specified in swagger. The documentation for that type will mention the possible valid value (good user experience).

### CODE REVIEW

**Comment by amarzavery** [comment]
@stankovski - Can you please review?

This file  "AutoRest/Modelers/Swagger/ObjectBuilder.cs" has a tiny change to solve the issue.

**Comment by amarzavery** [comment]
@devigned 
There are 40 ruby test failures with similar Error message. Can you please help :) ?
```
 1) Complex should create test service
19:19:45      Failure/Error: @client = AutoRestComplexTestService.new(@credentials, @base_url)
19:19:45 
19:19:45      NameError:
19:19:45        undefined local variable or method `preview' for #<ComplexModule::AutoRestComplexTestService:0x29ada88>
19:19:45      # ./RspecTests/Generated/complex/body_complex/auto_rest_complex_test_service.rb:69:in `initialize'
19:19:45      # ./RspecTests/complex_spec.rb:19:in `new'
19:19:45      # ./RspecTests/complex_spec.rb:19:in `block (2 levels) in <module:ComplexModule>'
19:19:45 
```

**Comment by devigned** [comment]
Well... All PRs accepted have been green. How did this start happening?

**Comment by devigned** [comment]
I am not rereading this and my previous message was not within context. I'm happy to help.

**Comment by amarzavery** [comment]
closing in favor of #828.

**Pull request closed without merging**
