### PR TITLE
Issue 944

### PR DESCRIPTION
**Pull request by John-Hart**
Fixes Issue #944 by catching the JSONException that may occur on a Non-Success StatusCode when attempting to Deserialize the HTTPResponse.Content when it is not JSON. 

Also  added a new LongRunningOperations test to verify that a CloudException is still thrown in this case.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@John-Hart__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (johnhart). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by jianghaolu** [comment]
Please pull from upstream master to get a hot fix in Java. Thanks!

**Comment by John-Hart** [comment]
@azuresdkci retest this please

**Comment by John-Hart** [comment]
reopened - closed in error

**Comment by azurecla** [comment]
Hi __@John-Hart__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (johnhart). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by John-Hart** [comment]
@azuresdkci - Test this please!

**Comment by amarzavery** [comment]
@azuresdkci - Test this please!

**Pull request merged**
