### PR TITLE
Support rfc1123 datetime in AzureCodeGenerator for Csharp

### PR DESCRIPTION
**Pull request by matthchr**
We missed an include in the MethodGroup files, which is now fixed

### CODE REVIEW

**Comment by matthchr** [comment]
@stankovski @yugangw-msft Can you merge this?  It is a small fix.

**Comment by devigned** [comment]
did pr this fail based on code regeneration?

**Comment by stankovski** [comment]
Travis was fixed recently. Can you check why it's failing?

**Comment by devigned** [comment]
https://github.com/Azure/autorest/blob/dev/ClientRuntimes/CSharp/Microsoft.Rest.ClientRuntime.Tests/JsonSerializationTests.cs#L261

That should not have environment specific newlines, @stankovski.

**Comment by matthchr** [comment]
@devigned @stankovski Yes, it looks like the test at the place David points out should have Environment.NewLine not \r\n -- I can fix it in this PR.

**Comment by devigned** [comment]
I'm more concerned about why it was passing and just failed meow. Cat there be a problem in the build?

**Comment by matthchr** [comment]
@devigned @stankovski Fixed the test failure -- travis is passing now.

**Comment by devigned** [comment]
Restarting build... Looks like it hung

**Comment by devigned** [comment]
Thank you, @matthchr!

**Pull request merged**
