### PR TITLE
msrestazure 0.4.1

### PR DESCRIPTION
**Pull request by lmazuel**
@annatisch fix for https://github.com/Azure/autorest/issues/1133

+

ChangeLog for 0.4.1 release

### CODE REVIEW

**Comment by lmazuel** [comment]
Released:
https://pypi.python.org/pypi/msrestazure/0.4.1

**Comment by tbombach** [comment]
@azuresdkci retest this please

**Comment by lmazuel** [comment]
@azuresdkci retest this please

**Comment by lmazuel** [comment]
@tbombach could you please merge this one? This correspond to published packages on the Python repository Pypi, so we don't want another PR being merged in the Python client runtime before this one, otherwise the commit history will be false.
Maybe @annatisch could help you if you think the build is failed because of the content.
Thanks,

**Comment by annatisch** [comment]
@tbombach, @lmazuel,
Not sure about travis, but the errors on jenkins do appear to be related to the Python tests. I'll take a look!

**Comment by fearthecowboy** [comment]
@azuresdkci retest this please

**Comment by lmazuel** [comment]
@tbombach @fearthecowboy Finally, we fixed the tests which were incorrects. CI power \m/

**Comment by lmazuel** [comment]
@tbombach Could you please merge this one while it's green? :)

**Pull request merged**
