### PR TITLE
Allow c# generation of string List parameters with formatted types

### PR DESCRIPTION
**Pull request by saikatguha**
Supports known formatted string primaryTypes in collection parameters.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@saikatguha__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@saikatguha__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by fearthecowboy** [comment]
Hey @saikatguha,

Could you provide some unit testing for this as well?

The simplest thing to do is create a swagger spec like :
   https://github.com/Azure/autorest/blob/master/src/generator/AutoRest.CSharp.Unit.Tests/Resource/Bug1285.yaml

then create a unit test like :
 https://github.com/Azure/autorest/blob/master/src/generator/AutoRest.CSharp.Unit.Tests/Bug1285.cs 

(give them the same class/filename as each other)
and then you can use reflection to verify the output class is generated like you want:
(see example ) https://github.com/Azure/autorest/blob/master/src/generator/AutoRest.CSharp.Unit.Tests/Bug1285.cs#L66

**Comment by hovsepm** [comment]
@azuresdkci test this please

**Pull request closed without merging**
