### PR TITLE
Fix two warnings, tiny doc editing

### PR DESCRIPTION
**Pull request by brodyberg**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@brodyberg__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by stankovski** [comment]
@brodyberg Thanks for the PR! The change looks good.

**Comment by stankovski** [comment]
@azuresdkci test this please

**Comment by azurecla** [comment]
Hi __@brodyberg__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by amarzavery** [comment]
@brodyberg - Can you sign the CLA as indicated by the bot?

**Comment by brodyberg** [comment]
@amarzavery I have joined the Azure Group & unified my account @devigned - are there additional steps?

**Comment by azurecla** [comment]
Hi __@brodyberg__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (brodyb). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Pull request merged**
