### PR TITLE
Small docs typo fix: swager --> swagger

### PR DESCRIPTION
**Pull request by kfcampbell**
Hi, I've been reading through the project's documentation recently and I noticed a couple of instances of "swager" when I'm reasonably sure "swagger" is meant. 

Outside of the first PR commit, there are 3 more instances: one each in packages/extensions/core/CHANGELOG.json, packages/extensions/core/CHANGELOG.md, and packages/libs/configuration/src/configuration-schema/autorest-configuration-schema.ts. 

I've opted to avoid replacing the first two out of historical record and the last out of the fear that it may be a breaking change. Please let me know if you'd like me to update those instances as well!

### CODE REVIEW

**Comment by kfcampbell** [comment]
Interesting...it looks like the CI validation is failing due to linting linking to a repository with the "Internal" visibility. What would you like me to do about this?

**Comment by kfcampbell** [comment]
Oh no! I think this is still relevant. I missed this notification earlier somehow.

**Comment by kfcampbell** [comment]
/reopen

I'm unable to remove the no-recent-activity label unfortunately.

**Comment by timotheeguerin** [comment]
Hey @kfcampbell  sorry missed this PR, this looks good, there is an issue with the doc linting at the moment so just ignore that. I'll merge

**Pull request merged**
