### PR TITLE
[Go] Workaround golint stuttering

### PR DESCRIPTION
**Pull request by mcardosos**
When a model / enum / method name starts with the package name, golint will notice the stuttering. For example: `compute.ComputeVM`. Golint will suggest something like `compute.VM`. The problem is when the name of the model / enum /method is exaclty the same as the package. AutoRest currently generates `containerservice.ContainerServiceType`. With this change, it would generate `containerservice.TypeContainerService`

### CODE REVIEW

**Comment by mcardosos** [comment]
Please, take a look :3 @vishrutshah @jhendrixMSFT @garimakhulbe

**Comment by jhendrixMSFT** [comment]
LGTM

**Comment by ahmetalpbalkan** [comment]
You can disable stuttering warnings easily. They're not the end of the world. First of all `type containerservice.ContainerServiceType` sounds really weird. Why is there a `Type` at the end? That said, `containerservice.TypeContainerService` isn't any less weird. 

I'm okay with stuttering here.

**Comment by mcardosos** [comment]
I agree it sounds super weird. For me, the ideal thing would be for it to be named just `ContainerService`. Do you know how to disable the stuttering warnings?

**Comment by ahmetalpbalkan** [comment]
`go lint | grep -v stutter`

**Comment by mcardosos** [comment]
Interesting thing, golint won't complain if the struct has exactly the same name as the package :D So yeah, the struct can be named `ContainerService` without problem :3

**Comment by tbombach** [comment]
@fearthecowboy fyi, this is a change to the Go namer

**Pull request merged**
