### PR TITLE
Improvements for Ruby generator and client runtime

### PR DESCRIPTION
**Pull request by nicklebedev37**
The PR includes the following work items:

1. Added specs for both MsRest and MsRestAzure.
2. Reworked dependencies to be added via Autoload instead of Require.
3. Changed Ruby test run to be done via command line running.
4. Reworked Ruby test files generation to be done via gulp.
5. Corrected readme and gems definitions.
6. Various minor code cleanup and fixes.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@nicklebedev37__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (nick.lebedev@akvelon.com). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by nicklebedev37** [comment]
cortana retest please

**Comment by devigned** [comment]
please update the pull request

**Comment by devigned** [comment]
Nice job!! I'm super excited to get these changes merged!

**Comment by nicklebedev37** [comment]
Thanks, David, sounds awesome!

**Pull request merged**
