### PR TITLE
Change Default Value to true for add-credentials [TS/JS SDKs]

### PR DESCRIPTION
**Pull request by sarangan12**
An issue has been created in the TS SDK Generator repository - https://github.com/Azure/autorest.typescript/issues/1416 that pointed the issue that the default value of add-credentials is set to true, whereas the documentation (file modified in this PR) indicates that default value is false. 

Actually, the default value is true. The documentation seems to be incorrect. I am creating this issue to fix the documentation. 

@joheredi @xirzec Please review and approve the PR. Thanks

### CODE REVIEW

**Comment by timotheeguerin** [comment]
Is this true for all languages using `--add-credentials` this is a shared flag.

**Comment by sarangan12** [comment]
> Is this true for all languages using `--add-credentials` this is a shared flag.

Per the documentation, .NET/Java/Go do not have this flag.

**Comment by timotheeguerin** [comment]
> > Is this true for all languages using `--add-credentials` this is a shared flag.
> 
> Per the documentation, .NET/Java/Go do not have this flag.

I see, all good then it was hard to see the diff of what was actually changed.

The formatter is failing, please run `rush format`

**Comment by sarangan12** [comment]
Ran `rush format` and pushed the changes

**Review by timotheeguerin — APPROVED** [review]

**Pull request merged**
