### PR TITLE
Updated the error message to include the method name and property when the NextLink property could not be found

### PR DESCRIPTION
**Pull request by John-Hart**
Fix for issue #1023

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@John-Hart__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by fearthecowboy** [comment]
@azuresdkci retest this please

**Comment by fearthecowboy** [comment]
It's failing on the Travis build, but that appears to be unrelated to the code.

**Comment by fearthecowboy** [comment]
I'm going to merge this anyway, given that the windows build is successful.

**Pull request merged**
