### PR TITLE
Add download streaming support

### PR DESCRIPTION
**Pull request by jianghaolu**
https://github.com/Azure/autorest/issues/769

### CODE REVIEW

**Comment by jianghaolu** [comment]
@matthchr

**Comment by matthchr** [comment]
@jianghaolu I skipped this test in the "Coverage" test too -- can you undo that skip?

This looks good to me (provided travis passes) other than that.

**Comment by jianghaolu** [comment]
@azuresdkci retest this please **on another slave**

**Comment by jianghaolu** [comment]
Looks like my downloading client is capable of killing the server on Linux. Very interesting.

**Comment by jianghaolu** [comment]
Reproduced on a Linux machine. Upgrading node version to 4.x resolves the issue.

@amarzavery Do you see any potential issue using node 4.x on Travis? Thanks!

**Comment by amarzavery** [comment]
@jianghaolu - Upgrading to 4.x should be fine.

**Comment by jianghaolu** [comment]
Thanks! Merging.

**Pull request merged**
