### PR TITLE
[Java] AutoRest changes by runtime changes

### PR DESCRIPTION
**Pull request by jianghaolu**

### CODE REVIEW

**Comment by fearthecowboy** [comment]
@azuresdkci retest this please

**Comment by jianghaolu** [comment]
@fearthecowboy there's additional setup needed in the gulpfile to make this pass. I'll add those in later.

**Comment by fearthecowboy** [comment]
Ok; I was restarting some builds to see if I can track down some problems in the CI system this morning.

Oh, btw, I "Maven'd" all the build servers yesterday. Your script went smooth as butter. 🍬

**Comment by jianghaolu** [comment]
@azuresdkci retest this please

**Comment by jianghaolu** [comment]
@fearthecowboy One change I made outside the Java world is here: https://github.com/Azure/autorest/pull/1703/files#diff-7279abdb89357e6191e713c62bfd9484R31. This effectively yield this result in generated code: https://github.com/Azure/autorest/pull/1703/files#diff-e79c1dd0f1ca0d227193d0f68f03073dL587.

Otherwise all changes are in Java generators and mainly consist of:
- naming changes for consistency (use withXyz() for setters and xyz() for getters)
- use `RestClient` for generic clients as well (used to be only used by Azure generator)
- Use a generic `serializerAdapter()` so that XML is possible in the future

**Comment by olydis** [comment]
@jianghaolu Looks good, 0 changes in any non-Java generated code! 👍 

By the way, I think the expected code of Java tests isn't regenerated yet, run `gulp regenerate:expected` and you should see some Java files change.

**Comment by jianghaolu** [comment]
Cool! I just regenerated the samples!

**Comment by jianghaolu** [comment]
Thanks guys! 🏆

**Pull request merged**
