### PR TITLE
pin version of source-map and types file 

### PR DESCRIPTION
**Pull request by fearthecowboy**
-- the new one removes the namespace. (//cc FYI @olydis)

### CODE REVIEW

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by fearthecowboy** [comment]
> win32-x64 restart

**Comment by fearthecowboy** [comment]
Admin merging -- the regenerate has some quantum-fluctuation timing difference on windows that is unimportant.  need fix now.

**Comment by fearthecowboy** [comment]
Overriding -- need in now. (dunno why win build is jerking me around)

**Pull request merged**
