### PR TITLE
Fix Swagger SchemaResolver to allow indirectness/inheritence when matching

### PR DESCRIPTION
**Pull request by TimLovellSmith**
Because properties may be defined by chains of indirect references to some type which inherits from another compatible type found by chains of indirect references, and that should be fine!

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@TimLovellSmith__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (tilovell). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by TimLovellSmith** [comment]
CI build seems to have encountered problems downloading something - how do I get it to try again?

**Comment by TimLovellSmith** [comment]
It looks like I broke  ClientModelWithCircularDependencyThrowsError [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.ArgumentException)
      Actual:   (No exception was thrown)

I am really not sure if this is really because the change I made is wrong. The test case includes a circular referenced based on a cycle of 'allOf' references, but I think the problem is that the code of Dereference, is designed to follow the chain of 'ref' references to its ultimate conclusion: not 'allOf' references, and therefore doesn't detect the circularity.

**Comment by TimLovellSmith** [comment]
Note that circular 'allOf' is not necessarily even impossible to resolve in the swagger model - you can just follow the circle until it repeats itself, and assume the result is the closure of all the things visited. Some language generators may have trouble with generating code to reflect that, however. :-)

**Comment by TimLovellSmith** [comment]
And circular 'ref' from type to itself if via properties list is also not necessarily impossible to resolve - it should correspond to recursive data structures like binary trees, etc.

**Comment by TimLovellSmith** [comment]
I'm going to go ahead and add some logic to satisfy the test for now, even though I'm not sure its a great test, it seems like path of least resistance.

**Comment by tbombach** [comment]
@azuresdkci add to whitelist

**Comment by TimLovellSmith** [comment]
Hrm. Now I see code analysis failed...

replace the call to 'string.ToLower(CultureInfo)' with String.ToUpperInvariant().

**Comment by tbombach** [comment]
Could you simplify (and rename) the test swagger file so that it's more targeted for the scenario that it's validating? In the modeler tests, we're not testing against a real API specification, they're intended to be unit tests that make sure the correct model can be built for a given feature in Swagger

**Comment by TimLovellSmith** [comment]
@tbombach I've revised the pull request to simplify the test swagger file, and to add a full set of assertions for all the expected inheritance relationships.

**Comment by TimLovellSmith** [comment]
I'm hereby adding to the PR turning off CA1822 for test projects, because it makes the pull request process unnecessarily painful.

**Comment by TimLovellSmith** [comment]
Is the CI build flaky or what? '

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

The build has been terminated

'

**Comment by tbombach** [comment]
@TimLovellSmith The AutoRest repo was just switched from DNX to CoreCLR RC2, so that might be causing some flakiness. I'll watch your builds and restart them if they're failing for a transient reason or if it's unrelated to your changes

**Comment by TimLovellSmith** [comment]
@tbombach Thanks, CI checks passed!

**Comment by tbombach** [comment]
Merged. Thanks @TimLovellSmith for the contribution (and for working through the test flakiness)!

**Pull request merged**
