### PR TITLE
Split params in forms as well

### PR DESCRIPTION
**Pull request by timotheeguerin**
Test added to the testserver https://github.com/Azure/autorest.testserver/pull/275

### CODE REVIEW

**Comment by timotheeguerin** [comment]
@iscai-msft this PR makes form content-type payload act the same as multipart(As splitting the parameters). The change as of right now just set `isInMultipart: true` which I guess is incorect. So I am wondering first is do you need this property for the form payloads? If yes would maybe renaming this property to `isPartialBody` (or any other suggestion) would make sense?

**Review by daviwil — APPROVED** [review]

**Comment by iscai-msft** [comment]
@timotheeguerin `isPartialBody` sounds good to me! don't know yet if i need it for form payloads, haven't investigated that enough yet

**Comment by chamons** [comment]
https://github.com/Azure/autorest.testserver/pull/275 landed

**Comment by timotheeguerin** [comment]
Ok so now that I added the formdata spec, the regression test are failing as expected. I think from looking at it this is exactly what is to be expected from this change so unless someone has an objection I'll go forward.

**Pull request merged**
