### PR TITLE
Python update

### PR DESCRIPTION
**Pull request by lmazuel**
Some minor but interesting improvement to Python generation:
- Finally removed exception/credentials useless files
- Minor improvement to make pylint happy:
   - Import stdlib should be before external packages (import uuid)
   - Regexp strings should be prefixed by a r

A tiny change in tox.ini that I will discuss by email directly.

Thanks!

### CODE REVIEW

**Comment by lmazuel** [comment]
@olydis @fearthecowboy seems npm related :(

**Comment by olydis** [comment]
@lmazuel yep, investigating

**Comment by lmazuel** [comment]
@olydis any news on that? I just made some tests improvement that I would like to have for msrestazure testing. Thanks!

**Comment by olydis** [comment]
NodeJS people working on a fix, but not sure when that'll be done - will test your change locally and force merge if it's good

**Pull request merged**
