### PR TITLE
[Ruby - In Review] Be inclusive on which files to be bundled with gems

### PR DESCRIPTION
**Pull request by vishrutshah**
This change is about being inclusive on which files to be bundled with gems instead of rejecting files do not required from `git ls-files -z`

This way we will not unintentional bundle files like .gitignore, .travis.yml, Gemfile, *.gemspec etc... like we already did that until recently.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@vishrutshah__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by vishrutshah** [comment]
@veronicagg Please have a look into this PR when you get a chance. Thanks!

**Comment by veronicagg** [comment]
LGTM!

**Comment by vishrutshah** [comment]
Thanks for the review!!

**Pull request merged**
