### PR TITLE
[Do not merge] Streaming test

### PR DESCRIPTION
**Pull request by annatisch**

### CODE REVIEW

**Comment by hovsepm** [comment]
@azuresdkci retest this please

**Comment by annatisch** [comment]
@hovsepm  - I haven't been able to reliably reproduce this error, so I can close this PR for now and revisit this later. I've marked the test in Python as pending.

**Comment by fearthecowboy** [comment]
@annatisch can I close this PR? I'm about to do the code re-org and this will have to be re-applied against that if it's to be kept.

**Comment by annatisch** [comment]
No problem, done :)

**Pull request closed without merging**
