### PR TITLE
fix homepage urls in packages.json

### PR DESCRIPTION
**Pull request by forivall**
originally filed as Azure/azure-sdk-for-node#1872

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@forivall__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by amarzavery** [comment]
LGTM. Just an FYI, the test packages are private and never published.

**Comment by amarzavery** [comment]
@azuresdkci - Test this please

**Comment by forivall** [comment]
True, but I figured "why not update them anyways"?

**Pull request merged**
