### PR TITLE
set autorest.powershell v4 as default version loaded by autorest

### PR DESCRIPTION
**Pull request by dolauli**
Change the default version of autorest.powershell loaded by autorest from 3.0+ to 4.0+.

### CODE REVIEW

**Comment by dolauli** [comment]
@timotheeguerin Could you please help review and merge my change? We had a similar [update ](https://github.com/Azure/autorest/pull/3784)two years ago when we transitioned autorest.powershell from 2.1+ to 3.0+.

BTW, the CI failure seems not caused by my change.

**Review by timotheeguerin — APPROVED** [review]

**Comment by timotheeguerin** [comment]
Have a pr here that should solve the ci bug, https://github.com/Azure/autorest/pull/4794

but somehow I cannot merge PRs anymore in autorest. MIght have been due to the permission cleanup

**Comment by dolauli** [comment]
> Have a pr here that should solve the ci bug, #4794
> 
> but somehow I cannot merge PRs anymore in autorest. MIght have been due to the permission cleanup

Hi Tim, Thanks a lot for helping review the PR. Do you know who may have the permission to merge the PR? Or I have to wait for you to re-apply the permission.

**Comment by timotheeguerin** [comment]
I got the permission back but the failure is still happening, now seems to be a problem with `@autorest/python` installing

**Pull request merged**
