### PR TITLE
[WIP/Do Not Merge] Support char format and new build scripts.

### PR DESCRIPTION
**Pull request by fearthecowboy**

### CODE REVIEW

**Comment by fearthecowboy** [comment]
@azuresdkci retest this please

**Comment by gitfool** [comment]
@fearthecowboy Would it be worth adding a format for the equivalent of DateTimeOffset while you're in there? The all or nothing approach of the command-line switch seems redundant now, and having the ability to mix and match as required would be more flexible.

**Comment by fearthecowboy** [comment]
@azuresdkci retest this please

**Comment by fearthecowboy** [comment]
killing this one, will re issue based on new reorg.

**Pull request closed without merging**
