### PR TITLE
Ruby - Adding warning instead of Validation failure.

### PR DESCRIPTION
**Pull request by vishrutshah**
Adding warning instead of Validation failure when unknown property found on object.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@vishrutshah__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by devigned** [comment]
LGTM

**Comment by veronicagg** [comment]
@vishrutshah looks good!

**Comment by vishrutshah** [comment]
Thanks for the review!!

**Pull request merged**
