### PR TITLE
fix relative paths, accept colon

### PR DESCRIPTION
**Pull request by fearthecowboy**

### CODE REVIEW

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by fearthecowboy** [comment]
> linux-x64 restart
> win32-x64 restart

**Comment by fearthecowboy** [comment]
> linux-x64 restart

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Pull request closed without merging**
