### PR TITLE
Remove Python msrest/msrestazure from Autorest repo

### PR DESCRIPTION
**Pull request by lmazuel**
Python msrest migrated:
https://github.com/Azure/msrest-for-python

Trying to remove it from here and having CI happy at the same time.

FYI @annatisch

### CODE REVIEW

**Comment by fearthecowboy** [comment]
LGTM 👍

**Comment by annatisch** [comment]
Me too 👍

**Comment by lmazuel** [comment]
Hi @tbombach could you merge this one?
Then, I will start moving msrestazure out too.

Thanks!

**Comment by lmazuel** [comment]
Python msrestazure migrated:
https://github.com/Azure/msrestazure-for-python/

**Comment by tbombach** [comment]
Merged!

**Pull request merged**
