### PR TITLE
Python: Make AzureOperationPoller thread a daemon thread

### PR DESCRIPTION
**Pull request by tjprescott**
See item #1378. This PR doesn't make the use of daemon threads configurable, but that is an option too. This is the simplest fix.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@tjprescott__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (trpresco). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by johanste** [comment]
Is http://bugs.python.org/issue1856 of concern with this change (for Python [2.x)?]

**Comment by tbombach** [comment]
@azuresdkci test this please!

**Comment by tbombach** [comment]
@annatisch @lmazuel Is this something we want to add to the python client runtime?

**Comment by lmazuel** [comment]
Hum.... I see your bug report @tjprescott and it makes senses. Daemon thread cannot prevent the main executable to quit. I think it's relevant. Good point.
@johanste @tjprescott did you update msrestazure on a virtualenv to confirm 100% it solves your Ctrl+C problem?

**Comment by lmazuel** [comment]
And I'm thinking it's one of the reason I got the test UI in PTVS unable to launch my tests again when I cancel a unittest that use LRO (need to quit PTVS and relaunch it). @zooba what do you think?

**Comment by tjprescott** [comment]
@lmazuel I tested the fix's ability to break out of our CLI in both Python 2.7 and 3.5 virtual environments and it worked as expected. On Linux you need only press Ctrl+C once and it breaks to command line. On CMD you press it once and you'll get the "Terminate batch operation Y/N" prompt which is much better than before where you had to press it multiple times and still incur a lengthy polling delay before you would get that prompt.

This is the simplest fix but I don't know that there wouldn't be applications that specifically would NOT want daemon threads. If that is the case it might be better to make it an optional parameter when the LRO is created.

**Comment by lmazuel** [comment]
@annatisch I think it's best to accept the PR, it should be the default. However, we might want to add a configuration item in the azure_configuration object for this. In this case, we create another issue (low priority) like "Add daemon thread LRO parameter to azure_configuration"

**Comment by annatisch** [comment]
@lmazuel  Sounds good :)

**Comment by lmazuel** [comment]
Created the issue for conf: https://github.com/Azure/autorest/issues/1416
@tbombach you can merge when you want :)
thanks @tjprescott for the PR!

**Comment by tbombach** [comment]
Merged

**Pull request merged**
