### PR TITLE
Set TS version to latest

### PR DESCRIPTION
**Pull request by joheredi**
Point TS plugin version to latest in NPM

https://www.npmjs.com/package/@autorest/typescript/v/latest

### CODE REVIEW

**Review by timotheeguerin — APPROVED** [review]

**Comment by timotheeguerin** [comment]
Need to run `rush change`

**Comment by joheredi** [comment]
> Need to run `rush change`

This is a very cool way to manage changelogs!

**Comment by joheredi** [comment]
@timotheeguerin I don't seem to have permission to merge. Would you mind merging when you get a chance please?

**Comment by timotheeguerin** [comment]
> > Need to run `rush change`
> 
> This is a very cool way to manage changelogs!

Yeah forces PRs to have change logged and then generate nice changelog on release. If you are using rush in the @autorest/typescript you should look into using it.

**Pull request merged**
