### PR TITLE
TS updates to tests and some TS related codegen changes for d.ts files

### PR DESCRIPTION
**Pull request by amarzavery**

### CODE REVIEW

**Comment by amarzavery** [comment]
@balajikris - Please review

**Comment by balajikris** [comment]
I understand the change but I don't know why this broke suddenly? what changed?

**Comment by balajikris** [comment]
does this mean our current .d.ts files are broken somehow?

**Comment by balajikris** [comment]
LGTM

**Comment by olydis** [comment]
@balajikris this broke because `tsc` got smarter/stricter with type checking, and uncovered some type errors that went unnoticed before

**Pull request merged**
