### PR TITLE
Added a return of an ExitCode to Autorest.exe

### PR DESCRIPTION
**Pull request by John-Hart**
Fixes Issue #935 by returning an integer ExitCode from Autorest.exe

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@John-Hart__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (johnhart). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by John-Hart** [comment]
@azuresdkci retest this please

**Comment by amarzavery** [comment]
@azuresdkci - Add to white list.

**Comment by amarzavery** [comment]
@azuresdkci  - Test this please!

**Pull request merged**
