### PR TITLE
support for colliding x-ms-discriminator-value for discriminators in node.js

### PR DESCRIPTION
**Pull request by amarzavery**

### CODE REVIEW

**Comment by brjohnstmsft** [comment]
Is there an Issue describing why this change is needed?

**Comment by amarzavery** [comment]
We dont have an issue describing the problem. However, I can describe it here. The ServiceFabric team, names their models as an Enum of Integers on the wire ('x-ms-discriminator-value': 1) to differentiate between different sub models of a parent model. Now they use same numbers in different inheritance chains. This causes a collision in the discriminators object in models/index.js.
 Example:
```
. . .
exports.discriminators = {
  'HealthEvaluation' : exports.HealthEvaluation,
  '1' : exports.EventHealthEvaluation,
  '2' : exports.PartitionsHealthEvaluation,
  '3' : exports.ReplicasHealthEvaluation,
  '4' : exports.DeployedServicePackagesHealthEvaluation,
  '5' : exports.DeployedApplicationsHealthEvaluation,
  '6' : exports.ServicesHealthEvaluation,
  '7' : exports.NodesHealthEvaluation,
  '8' : exports.ApplicationsHealthEvaluation,
  '9' : exports.UpgradeDomainNodesHealthEvaluation,
  '10' : exports.UpgradeDomainDeployedApplicationsHealthEvaluation,
  '11' : exports.SystemApplicationHealthEvaluation,
  '12' : exports.PartitionHealthEvaluation,
  '13' : exports.ReplicaHealthEvaluation,
  '14' : exports.DeployedServicePackageHealthEvaluation,
  '15' : exports.DeployedApplicationHealthEvaluation,
  '16' : exports.ServiceHealthEvaluation,
  '17' : exports.NodeHealthEvaluation,
  '18' : exports.ApplicationHealthEvaluation,
  '19' : exports.DeltaNodesCheckHealthEvaluation,
  '20' : exports.UpgradeDomainDeltaNodesCheckHealthEvaluation,
  '21' : exports.ApplicationTypeHealthEvaluation,
  'ServiceGroupDescription' : exports.ServiceGroupDescription,
  '1' : exports.StatelessServiceGroupDescription,
  '2' : exports.StatefulServiceGroupDescription,
  'ServiceDescription' : exports.ServiceDescription,
  '1' : exports.StatelessServiceDescription,
  '2' : exports.StatefulServiceDescription
};
```
As you can see: HealthEvaluation has submodels with 1, 2, etc. and ServiceGroupDescription and ServiceDescription also have 1, 2 as submodels.

So to solve this problem, I have added the uber parent (final BaseModelType) in the discriminator keys to resolve the collision and have made necessary changes in the serialization/deserialization logic in the client runtime to get the right model class based on the provided value in the discriminator property.

The new discriminator object would look like this:
```
...
exports.discriminators = {
  'HealthEvaluation' : exports.HealthEvaluation,
  'HealthEvaluation.1' : exports.EventHealthEvaluation,
  'HealthEvaluation.2' : exports.PartitionsHealthEvaluation,
  'HealthEvaluation.3' : exports.ReplicasHealthEvaluation,
  'HealthEvaluation.4' : exports.DeployedServicePackagesHealthEvaluation,
  'HealthEvaluation.5' : exports.DeployedApplicationsHealthEvaluation,
  'HealthEvaluation.6' : exports.ServicesHealthEvaluation,
  'HealthEvaluation.7' : exports.NodesHealthEvaluation,
  'HealthEvaluation.8' : exports.ApplicationsHealthEvaluation,
  'HealthEvaluation.9' : exports.UpgradeDomainNodesHealthEvaluation,
  'HealthEvaluation.10' : exports.UpgradeDomainDeployedApplicationsHealthEvaluation,
  'HealthEvaluation.11' : exports.SystemApplicationHealthEvaluation,
  'HealthEvaluation.12' : exports.PartitionHealthEvaluation,
  'HealthEvaluation.13' : exports.ReplicaHealthEvaluation,
  'HealthEvaluation.14' : exports.DeployedServicePackageHealthEvaluation,
  'HealthEvaluation.15' : exports.DeployedApplicationHealthEvaluation,
  'HealthEvaluation.16' : exports.ServiceHealthEvaluation,
  'HealthEvaluation.17' : exports.NodeHealthEvaluation,
  'HealthEvaluation.18' : exports.ApplicationHealthEvaluation,
  'HealthEvaluation.19' : exports.DeltaNodesCheckHealthEvaluation,
  'HealthEvaluation.20' : exports.UpgradeDomainDeltaNodesCheckHealthEvaluation,
  'HealthEvaluation.21' : exports.ApplicationTypeHealthEvaluation,
  'ServiceGroupDescription' : exports.ServiceGroupDescription,
  'ServiceGroupDescription.1' : exports.StatelessServiceGroupDescription,
  'ServiceGroupDescription.2' : exports.StatefulServiceGroupDescription,
  'ServiceDescription' : exports.ServiceDescription,
  'ServiceDescription.1' : exports.StatelessServiceDescription,
  'ServiceDescription.2' : exports.StatefulServiceDescription,
  'ServiceUpdateDescription' : exports.ServiceUpdateDescription,
  'ServiceUpdateDescription.1' : exports.StatelessServiceUpdateDescription,
  'ServiceUpdateDescription.2' : exports.StatefulServiceUpdateDescription,
  'ServiceGroupUpdateDescription' : exports.ServiceGroupUpdateDescription,
  'ServiceGroupUpdateDescription.1' : exports.StatelessServiceGroupUpdateDescription,
  'ServiceGroupUpdateDescription.2' : exports.StatefulServiceGroupUpdateDescription
};
```

**Comment by brjohnstmsft** [comment]
Thanks. I recall the discriminators in Ruby are also managed via some kind of lookup table. Could this issue affect Ruby code gen as well?

**Comment by amarzavery** [comment]
@azuresdkci - Test this please!

**Comment by amarzavery** [comment]
Ruby has a discriminator map at the topmost basemodel type. Hence they should be fine.

```
  class Fish
      @@discriminatorMap = Hash.new
      @@discriminatorMap["Fish"] = "fish"
      @@discriminatorMap["salmon"] = "salmon"
      @@discriminatorMap["shark"] = "shark"
      @@discriminatorMap["sawshark"] = "sawshark"
      @@discriminatorMap["goblin"] = "goblinshark"
      @@discriminatorMap["cookiecuttershark"] = "cookiecuttershark"
```

**Comment by brjohnstmsft** [comment]
Cool, thanks for confirming!

**Comment by amarzavery** [comment]
@azuresdkci - Test this please!

**Comment by amarzavery** [comment]
Merging this as Jeffrey Chen needs it urgently. The Travis CI is passing. Jenkins is flaky due to different setup issues.

**Pull request merged**
