### PR TITLE
#83 - Added support for decimal type

### PR DESCRIPTION
**Pull request by jkonecki**
Fix for issue #83

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@jkonecki__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by hovsepm** [comment]
@azuresdkci test this please....

**Comment by hovsepm** [comment]
@jkonecki,
Could you also make a few more changes:
1. Update NodeJS and Ruby CodeNamers to account for new decimal type.
2. Update scenario tests to verify decimals are properly handled in each respective language (they are defined in AutoRest\Generators\AcceptanceTests folder and implemented in each language generator test project) 
3. Regenerate code by running  tools\RegenerateExpectedClasses.ps1
4. Run code analysis for entire solution and address issues.

**Comment by azurecla** [comment]
Hi __@jkonecki__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by jkonecki** [comment]
I've updated code namers for NodeJs and Ruby. I don't know Ruby and don't have nodejs installed so I'm not confident preparing acceptance tests for them.
I've executed ps scripts and have 80 new files in `AutoRest\Generators\Ruby\Ruby.Tests\Expected\RspecTests\Models` folder. Do you want me to check them in as well?

**Comment by stankovski** [comment]
Cortana test this please...

**Comment by hovsepm** [comment]
Cortana retest this please

**Comment by devigned** [comment]
please update the pull request

**Comment by devigned** [comment]
Since this has not be carried forward, I'm going to close this pull request. Please reopen if the intention is to finish the functionality.

**Comment by jkonecki** [comment]
Hello @devigned - what do you mean by not carried forward?

**Comment by devigned** [comment]
- it has not been updated from latest dev, so can't be merged
- there are no integration tests, so we don't know if the generated code will form (serialize, etc) proper http requests / responses

I'm not so concerned that the pull request only targets c#, though it would be nice to have the functionality across each generator. It seems unfair to expect one person to implement generation features across multiple languages. I'm more concerned about end-to-end validation of the code generator and generated clients.

If the pull request was updated to the latest dev and passing integration + unit test, we'd definitely get it merged.

The integration tests I'm speaking of are tests that generate out a client, build the client, then test the client against the node test server in https://github.com/Azure/autorest/tree/dev/AutoRest/TestServer. These tests verify serialization and edge cases (overflows, etc) for the generators. Basically, if these tests pass, we feel the generators are going to produce working clients. The unit tests are good, but the end-to-end tests of the generated code is the true litmus test.

I hope didn't come off as coarse or curt in the previous comment. It's quite hard to provide color to interweb conversations. We like this pull request and are deeply thankful you took the time and care to craft it.

**Comment by jkonecki** [comment]
@devigned I've updated by branch with the latest dev. I'll submit the checkin with integration tests soon. Just to confirm: I need to add json file to `AutoRest\TestServer\swagger` and update mappings in gulpfile.js?

**Comment by devigned** [comment]
@jkonecki you are correct.

**Comment by jkonecki** [comment]
@devigned Added test cases for decimals. Could you please reopen this PR?

**Comment by jkonecki** [comment]
@devigned @hovsepm @stankovski Hello, it's been nearly a month since I've added test cases. Could someone please take a look at my PR?

**Comment by azurecla** [comment]
Hi __@jkonecki__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by devigned** [comment]
@jkonecki looks like you need to rebase in the changes from dev.

**Comment by stankovski** [comment]
@jkonecki Java tests seem to be failing

**Comment by jkonecki** [comment]
@stankovski Hello Denis, I tried to figure out what's going on with the failing test but I'm unable to fix is as I don't know Java.

**Comment by jkonecki** [comment]
Thank you, Denis! :-)

**Pull request merged**
