### PR TITLE
[DO NOT MERGE] Add "client-request-id" support in AutoRest

### PR DESCRIPTION
**Pull request by matthchr**
Existing AutoRest has a hardcoded "x-ms-clientrequestid" but that is not sufficient for all services (as some use "client-request-id" instead.  

This change adds an additional header to all requests.

If somebody has a suggestion for avoiding having 2 client request IDs all the time (which is confusing...) I'm open to it.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@matthchr__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (matthchr). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by brjohnstmsft** [comment]
Is there a way to let the caller specify client-request-id instead of always using a new GUID?

**Comment by matthchr** [comment]
@brjohnstmsft I think the intent is that the client-request-id (or x-ms-clientrequestid for that matter) should be specified as an optional header in the swagger spec.  That way it is just like any other header and would show up in the method signatures.  If it was specified in the method signature, then we would generate a guid, which would then be overwritten by the client specified header of the same name.

**Comment by devigned** [comment]
@Azure/adx-sdk-team thoughts on always providing two headers here?

**Comment by matthchr** [comment]
We discussed in our meeting and I will investigate a swagger extension for this to handle the return header case too.  I think that means we can hold off on merging this PR...

**Pull request closed without merging**
