### PR TITLE
Fixed ClientRuntime.Authentication versioning

### PR DESCRIPTION
**Pull request by hovsepm**

### CODE REVIEW

**Comment by fearthecowboy** [comment]
the purpose for the `-* ` is that during the build you can say `dotnet pack  --version-suffix preview ` and it will append the work `preview`

**Comment by fearthecowboy** [comment]
and if you're building via `build.proj` you can specify ` /p:VersionSuffix=preview`

**Comment by hovsepm** [comment]
@fearthecowboy so how do I fix publishing issue then? here what I get:
```
D:\workspace\autorest-publish\src\client\Microsoft.Rest.ClientRuntime.Azure.Authentication\bin\Release\Microsoft.Rest.ClientRuntime.Azure.Authentication.2.2.5-preview-0.17.nupkg
```

**Comment by hovsepm** [comment]
@fearthecowboy FYI http://azuresdkci.cloudapp.net/view/3-AutoRest/job/autorest-publish/95/console

**Comment by fearthecowboy** [comment]
LGTM. go ahead and Merge it

**Pull request merged**
