### PR TITLE
Pass through the connection verify setting for fetching the auth token

### PR DESCRIPTION
**Pull request by BurtBiel**
My team is unable to debug auth call with Fiddler because there is no way to turn off connection verification.  It turns out that verify can be set on the auth connection method, but it is not passed through to the fetch_token method.  This change adds that pass through.  Tested with Python 2.4/2.5.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@BurtBiel__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (burtbiel). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by yugangw-msft** [comment]
LGTM

**Comment by stankovski** [comment]
@azuresdkci add to whitelist

**Comment by stankovski** [comment]
@BurtBiel this PR broke a Python test
```
======================================================================
FAIL: test_user_pass_credentials (test.unittest_auth.TestInteractiveCredentials)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Azure/autorest/ClientRuntimes/Python/msrestazure/test/unittest_auth.py", line 317, in test_user_pass_credentials
    client_secret="secret", password='pass', resource='resource')
  File "/usr/lib/python3.5/unittest/mock.py", line 792, in assert_called_with
    raise AssertionError(_error_message()) from cause
AssertionError: Expected call: fetch_token('token_uri', client_id='id', client_secret='secret', password='pass', resource='resource', username='user')
Actual call: fetch_token('token_uri', client_id='id', client_secret='secret', password='pass', resource='resource', username='user', verify=True)
```

**Comment by yugangw-msft** [comment]
yes @BurtBiel  is working on it

**Comment by BurtBiel** [comment]
Are there any special setup steps to run the unit tests locally?  They all fail for me with missing module errors.  I'd like to debug on my machine before submitting another build if possible.  Thanks

**Comment by yugangw-msft** [comment]
@annatisch , could you suggest?

**Comment by annatisch** [comment]
I set up a virtual environment locally with the dependencies installed.

**Comment by annatisch** [comment]
There seems to be an added "test" at the beginning of unitest_auth.py which is causing it to fail:

File "/home/travis/build/Azure/autorest/ClientRuntimes/Python/msrestazure/test/unittest_auth.py", line 1, in <module>
    test#--------------------------------------------------------------------------
NameError: name 'test' is not defined

**Comment by BurtBiel** [comment]
It looks like the build is failing in the Java area, is that a known issue?  I assume it's unrelated to my Python changes

**Pull request merged**
