### PR TITLE
Add insights swagger spec test, add vm extensions to swagger and schema

### PR DESCRIPTION
**Pull request by daschult**

### CODE REVIEW

**Comment by fearthecowboy** [comment]
Hey @daschult,

We're going to be promoting the `RefactorCodeModel` branch to `master`  in the next day or so, and so I'm freezing any new commits to `master`

If you can rebuild this PR against that branch, it'd be great.

**Comment by daschult** [comment]
All updated.

**Comment by olydis** [comment]
Thanks @daschult! 👍

**Pull request merged**
