### PR TITLE
Warning message update

### PR DESCRIPTION
**Pull request by veronicagg**

### CODE REVIEW

**Comment by kirthik** [comment]
:shipit:  (of course when build passes :))

**Comment by olydis** [comment]
@azuresdkci test this please

**Comment by olydis** [comment]
@azuresdkci retest this please

**Comment by olydis** [comment]
Hey @azuresdkci!!! 😡 If you don't start building, we gotta talk.

**Comment by veronicagg** [comment]
thanks @olydis !

**Pull request merged**
