### PR TITLE
Fix missing part of urls in packages.json homepages

### PR DESCRIPTION
**Pull request by forivall**
My bad, I misentered the urls in #1412. Fixed _now_.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@forivall__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by amarzavery** [comment]
@azuresdkci - Test this please.

**Comment by fearthecowboy** [comment]
Hi @forivall, 

**In order for us to evaluate and accept your PR,** we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.

**Comment by fearthecowboy** [comment]
We're actually going to remove the runtime from here and reference it in the other repo.

**Pull request closed without merging**
