### PR TITLE
Regenerate samples

### PR DESCRIPTION
**Pull request by vishrutshah**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@vishrutshah__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by vishrutshah** [comment]
@fearthecowboy @veronicagg @John-Hart Once again i missed it to regenerate samples with my recent commits. Thanks to John for catching it. Could you guys please review the PR as you get a chance.

**Comment by John-Hart** [comment]
LKTM - thanks

**Comment by veronicagg** [comment]
@vishrutshah LGTM, thanks!

**Comment by vishrutshah** [comment]
Thanks for the review!!

**Pull request merged**
