### PR TITLE
Add UseDateTimeOffset option to CSharp generator

### PR DESCRIPTION
**Pull request by jhancock93**
Addresses issue #500 

Using -UseDateTimeOffset on the commandline will cause the CSharp generator to use DateTimeOffset? instead of DateTime? to model the Swagger date-time format.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@jhancock93__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@jhancock93__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by stankovski** [comment]
Thanks @jhancock93! The change looks good. Can you please add a test swagger under https://github.com/Azure/autorest/tree/master/AutoRest/Generators/CSharp/CSharp.Tests/Swagger with ["x-ms-code-generation-settings"](https://github.com/Azure/autorest/blob/master/Documentation/swagger-extensions.md#x-ms-code-generation-settings) element and generate a sample client by updating gulpfile.js (see https://github.com/Azure/autorest/blob/master/gulpfile.js#L278). Then please add an acceptance test in CSharp.Tests project to verify the new functionality.

**Comment by jhancock93** [comment]
OK, I will look into adding the test as suggested.

**Comment by jhancock93** [comment]
Pull request branch has been updated with a test swagger and the acceptance test as suggested.

**Pull request merged**
