### PR TITLE
#217 - Replaced XML comments with standard ones

### PR DESCRIPTION
**Pull request by jkonecki**
Fix for issue #217 and #205

### CODE REVIEW

**Comment by jkonecki** [comment]
Fix for issue #217

**Comment by azurecla** [comment]
Hi __@jkonecki__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by hovsepm** [comment]
@azuresdkci test this please....

**Comment by hovsepm** [comment]
@jkonecki, PR looks good! 
We will merge it once CLA is signed.

**Comment by hovsepm** [comment]
@jkonecki, 
We have made the similar fix in this PR https://github.com/Azure/autorest/pull/232 to unblock Azure Code Generation. Since you have not signed CLA yet we are unable to take yours and closing it.

**Comment by jkonecki** [comment]
I have signed CLA twice now.

**Comment by azurecla** [comment]
Hi __@jkonecki__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by hovsepm** [comment]
@jkonecki, we just verified it. Looks like there are some issue with CLA-bot and Github. Thanks for your contribution. I'll merge your PR.

**Pull request merged**
