### PR TITLE
Fixing bug 1880

### PR DESCRIPTION
**Pull request by dsgouda**
Added parameter description for base class parameters
@olydis PTAL

### CODE REVIEW

**Comment by dsgouda** [comment]
@azuresdkci Test this please

**Comment by msftgits** [comment]
Closing and re-opening to ping CLA bot.

**Comment by dsgouda** [comment]
@azuresdkci Test this please

**Comment by dsgouda** [comment]
@azuresdkci Test this please

**Comment by olydis** [comment]
@dsgouda your test case succeeds instantly on my machine (without pulling in any fix) so it is NOT a repro of bug #1880 (or bug #1880 is already fixed!?). Please confirm that the bug either is already fixed or create a repro.

**Comment by dsgouda** [comment]
Technically it isn't a bug its just that the description for base class parameters is missing on constructors
Do you see this happening without this fix?

**Comment by dsgouda** [comment]
Seems like we cannot repro this in the latest autorest build, closing this PR

**Pull request closed without merging**
