### PR TITLE
Added a test case to verify new file serialization functionality

### PR DESCRIPTION
**Pull request by avilensky**
This test case exercises the new file serialization functionality. Please, let me know if this looks OK to you. I'll be more than happy to make all necessary changes.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@avilensky__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by devigned** [comment]
Looks like it pretty close, but just a failure in travis.

**Comment by avilensky** [comment]
Fixed. I didn't realize I had to check in autorest generated files. Is it possible to rerun travis again?

**Comment by devigned** [comment]
rerunning travis

**Pull request closed without merging**
