### PR TITLE
#742: Hide DateTimeRfc1123

### PR DESCRIPTION
**Pull request by jianghaolu**
Issue #742

### CODE REVIEW

**Comment by jianghaolu** [comment]
@matthchr @xingwu1

**Comment by jianghaolu** [comment]
I still need to move the if conditions to a centralized place but the sample usage code in the test should stay unchanged.

**Comment by jianghaolu** [comment]
PR finalized.

**Comment by devigned** [comment]
I really like this PR. Great job encapsulating the DateTime details!

LGTM

**Comment by matthchr** [comment]
This looks good to me.

**Comment by jianghaolu** [comment]
Thanks guys! Merging.

**Pull request merged**
