### PR TITLE
Typescript

### PR DESCRIPTION
**Pull request by BretJohnson**
Added TypeScript support, generating .d.ts files along with the .js files already generated

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@bret-johnson__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by bret-johnson** [comment]
The Travis CI build failures all look like CI config issues, not issues with my change.

**Comment by devigned** [comment]
Looks like the build is red due to a mono issue in the nightly. It appears the 4.2 alpha is good. @matt-gibbs just created #340 with that change. 

Just wanted to let you know that it was not your change set.

**Comment by matt-gibbs** [comment]
Cortana, retest this please.

**Comment by BretJohnson** [comment]
Closing; generated a new pull request to replace this

**Pull request closed without merging**
