### PR TITLE
[Ruby] Bundling default ca-cert and exposing method for providing ssl options 

### PR DESCRIPTION
**Pull request by vishrutshah**
Windows Ruby developers frequently encounter issues while making https connections. 
```
Faraday::SSLError:
            SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
```
This implies that Ruby's OpenSSL was unable to verify the peer certificate while establishing an SSL connection.

References: 
http://www.rubyinside.com/how-to-cure-nethttps-risky-default-https-behavior-4010.html
http://stackoverflow.com/questions/19150017/ssl-error-when-installing-rubygems-unable-to-pull-data-from-https-rubygems-o
https://gist.github.com/luislavena/f064211759ee0f806c88

**Solution:**
To alleviate the problems we are bundling well-known [certificate ](https://curl.haxx.se/ca/cacert.pem) provided by Mozilla community and exposing method `use_ssl_options` through which users can provide Faraday ssl connection options for [Faraday connection](http://www.rubydoc.info/gems/faraday/Faraday#new-class_method) or opt-in to use the certificate bundled with client run-time.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@vishrutshah__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by veronicagg** [comment]
@vishrutshah LGTM, thanks! You may want to include some information in the readme file about this, so it's easier to discover for customers.

**Comment by vishrutshah** [comment]
@veronicagg Yes that's a good point. I'll add information to the readme.

**Comment by vishrutshah** [comment]
@veronicagg Feel free to skim over the README changes when you get a chance.

**Pull request merged**
