### PR TITLE
Added file serialization in C#

### PR DESCRIPTION
**Pull request by avilensky**
Added ability to serialize files into JSON format.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@avilensky__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by stankovski** [comment]
Thank you for the pull request! Can you add tests that verify your functionality under "...\Generators\CSharp\CSharp.Tests\AcceptanceTests.cs"?

**Comment by avilensky** [comment]
Should I create a new pull request after making necessary changes?

**Comment by stankovski** [comment]
Just push updates to your fork. They will appear in this pull request.

**Pull request closed without merging**
