### PR TITLE
[Linter] When parameters have refs, linter shuld not complain

### PR DESCRIPTION
**Pull request by vishrutshah**
fixes https://github.com/Azure/autorest/issues/2072

### CODE REVIEW

**Comment by olydis** [comment]
Can we move forward with this? :-)

**Comment by olydis** [comment]
@veronicagg Ah nice, which issue? I assume it's not https://github.com/Azure/autorest/issues/2072 since that is just talking about source paths lately - not the fact *that* those messages are emitted when they shouldn't. I'm just that curious since I'm currently assigned to a PR where >50% of all linter errors are false positives of this rule (that would be fixed by this PR, but I'm cool with any solution 😄).

**Comment by veronicagg** [comment]
@olydis I was referring to @2072. Could you share a link to the false positives you're referring to above?

**Comment by olydis** [comment]
@veronicagg Sure! :-) https://travis-ci.org/Azure/azure-rest-api-specs/jobs/223017830

**Comment by olydis** [comment]
@vishrutshah @veronicagg @sergey-shandar Can we close this one or do you wanna leave it open due to outstanding discussion or similar?

**Comment by vishrutshah** [comment]
@olydis If the fix cannot address the issue / improve linter rule then i'd keep the issue open and close the PR. Thoughts?

**Comment by olydis** [comment]
@vishrutshah sure thing, I'm fine with any solution. I just went through "old" PRs and wanted to make sure they are still open for a reason :-)

**Comment by vishrutshah** [comment]
@olydis This has been fixed with your new source mapping 💯 Thank You!!!

**Pull request closed without merging**
