### PR TITLE
Python generator updates

### PR DESCRIPTION
**Pull request by annatisch**
- Removal of explicit config object (breaking change)
- Serialization now supports dictionaries in place of complex objects
- Support for unix timestamps

### CODE REVIEW

**Comment by lmazuel** [comment]
LGTM

**Comment by tbombach** [comment]
LGTM. I don't know python, so I can't verify the config object change, but the changes to the generator and the base64url/unix time/serialization changes all look good.

**Comment by lmazuel** [comment]
I tested the Configuration changes in the whole Python SDK:
https://github.com/lmazuel/azure-sdk-for-python/commit/62cec94d79bddbd9810e806d8d4acd4e97e9ab76

And I'm ok with it

**Comment by annatisch** [comment]
@tbombach  - thanks, if you could merge when you're happy that would be great :)

**Comment by tbombach** [comment]
@azuresdkci retest this please!

**Comment by tbombach** [comment]
(I think a different AutoRest build configuration picked this PR up and wasn't configured for the automated tests, so I'll have it retest this and then merge when it finishes)

**Comment by tbombach** [comment]
Merged

**Comment by annatisch** [comment]
Awesome thank you!

**Comment by ThomasArdal** [comment]
@annatisch Could you share an example on how this can be utilized?

- Serialization now supports dictionaries in place of complex objects

**Comment by annatisch** [comment]
@ThomasArdal, sure thing!

So it used to be that if you had a request body with 1 required parameter and 2 optional parameters, this would need to be represented as an object, even if you only need it for setting that 1 required parameter:
Model:
```
class SampleRequestParameter(Model):
    def __init__(required, optional1=None, optional2=None):
        self.required = required
        self.optional1 = optional1
        self.optional2 = optional2
```
Method signature:
```
def post_sample_request(body_obj, custom_headers=None, raw=False, **operation_config):
```
Code:
```
body_arg = models.SampleRequestParameter("test_data")
response = client.operations.post_sample_request(body_arg)
```
The other option was to generate using the flatten flag set to 3, so the method signature would look like:
```
def post_sample_request(required, optional1=None, optional2=None, custom_headers=None, raw=False, **operation_config):
```
Now however you have the option to replace the object with a dictionary:
Method signature:
```
def post_sample_request(body_obj, custom_headers=None, raw=False, **operation_config):
```
Code:
```
response = client.operations.post_sample_request({'required':'test_data'})
```
This also works for nested complex objects, and mixes of objects/dicts:
```
body_arg = {'required':'test', 'optional1':{'complex_model':'2'}, 'optional2':models.TestModel(data=5)}
body_arg = models.SampleRequestParameter("test", optional2={'data':5})
```

I hope this helps! :)

**Comment by ThomasArdal** [comment]
@annatisch Thank you very much :smile:

**Pull request merged**
