### PR TITLE
Add platform in Python UserAgent

### PR DESCRIPTION
**Pull request by lmazuel**
Adding platform information in UserAgent for good metrics.

User-Agent looks like:
Python/3.5.1 (Windows-10-10.0.10586-SP0) requests/2.9.1 .............
Python/2.7.10 (Linux-4.2.0-30-generic-x86_64-with-Ubuntu-15.10-wily)  requests/2.10.0 .......

### CODE REVIEW

**Comment by tbombach** [comment]
LGTM

**Comment by hovsepm** [comment]
@azuresdkci retest this please

**Comment by hovsepm** [comment]
@azuresdkci retest this please

**Comment by tbombach** [comment]
Merged

**Pull request merged**
