### PR TITLE
Add a custom converter to address SecurityDefinition type property on deserialization

### PR DESCRIPTION
**Pull request by L3Z4**
Deserializing a json to a ServiceDefinition, the property "SecuritySchemeType" is not mapped from "type" element of the swagger.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@L3Z4__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@L3Z4__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by L3Z4** [comment]
Hi,
Is it possible to have some update about this PullRequest ?
Thanks.

**Comment by olydis** [comment]
see https://github.com/L3Z4/autorest/pull/1

**Comment by L3Z4** [comment]
Hi !
Thanks for your correction. I had accepted it.

Since my correction is a `JsonConverter`, I just changed the YAML file to a JSON file (simplified for containing only the case I want to test). 

I hope it's acceptable

**Comment by olydis** [comment]
Looks good to me! I expect this to be merged on Monday.
@fearthecowboy the CI build seems to fail because of Android SDK right now

**Comment by fearthecowboy** [comment]
@azuresdkci retest this please

**Pull request merged**
