### PR TITLE
Fixed typo error in Samples readme file.

### PR DESCRIPTION
**Pull request by phohtoo**
Just renamed pyhton to python. Thanks.

### CODE REVIEW

**Comment by olydis** [comment]
# publish job
~~~ Haskell
> waiting for PR to get merged or closed
~~~

**Comment by olydis** [comment]
# publish job
~~~ Haskell
> waiting for PR to get merged or closed
~~~

**Comment by olydis** [comment]
Hi @phohtoo, thanks for fixing this and sorry for not getting back earlier. As you may have noticed, CI has failed, which is because your change actually triggers generation of files that weren't there before, so our regression tests complain that "there are unexpected changes". We're actually improving that test right now, so it'll complain less in your case. Once that change is in, I'll come to this PR :)

**Comment by phohtoo** [comment]
Hi @olydis, noted with thanks for the info. In future, I will try my best to be able to contribute in other technical area of the project :)

**Comment by olydis** [comment]
# AutoRest automatic publish job
~~~ Haskell
> will publish once/if PR gets merged
~~~

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by olydis** [comment]
@phohtoo Glad to hear, thanks! :) Alrighty, let's get this PR in

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by olydis** [comment]
@phohtoo I've updated your PR in order to make CI happy - note that you have to sign the CLA in order to make contributions (only once, will be saved for any further contributions to our repos) 🙂

**Comment by phohtoo** [comment]
Thanks @olydis! Have signed CLA.

**Comment by olydis** [comment]
Thank *you* :)

**Pull request merged**
