### PR TITLE
Java Code Gen

### PR DESCRIPTION
**Pull request by ljhljh235**
Starting from 566ead4 all commits are acceptance test-driven and open ended, thus not required for this PR to be merged as long as the CI is passing.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ljhljh235__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (jianghlu). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by ljhljh235** [comment]
Cortana test this please

**Comment by ljhljh235** [comment]
Cortana retest this please

**Comment by ljhljh235** [comment]
<pre>
           _            _     _   _     _             _                     
  _ __ ___| |_ ___  ___| |_  | |_| |__ (_)___   _ __ | | ___  __ _ ___  ___ 
 | '__/ _ \ __/ _ \/ __| __| | __| '_ \| / __| | '_ \| |/ _ \/ _` / __|/ _ \
 | | |  __/ ||  __/\__ \ |_  | |_| | | | \__ \ | |_) | |  __/ (_| \__ \  __/
 |_|  \___|\__\___||___/\__|  \__|_| |_|_|___/ | .__/|_|\___|\__,_|___/\___|
                                               |_|                          
</pre>
<retest this please />

**Comment by ljhljh235** [comment]
<pre alt='retest this please'>
           _            _     _   _     _             _                     
  _ __ ___| |_ ___  ___| |_  | |_| |__ (_)___   _ __ | | ___  __ _ ___  ___ 
 | '__/ _ \ __/ _ \/ __| __| | __| '_ \| / __| | '_ \| |/ _ \/ _` / __|/ _ \
 | | |  __/ ||  __/\__ \ |_  | |_| | | | \__ \ | |_) | |  __/ (_| \__ \  __/
 |_|  \___|\__\___||___/\__|  \__|_| |_|_|___/ | .__/|_|\___|\__,_|___/\___|
                                               |_|                          
</pre>

**Comment by ljhljh235** [comment]
retest this please
<pre>
           _            _     _   _     _             _                     
  _ __ ___| |_ ___  ___| |_  | |_| |__ (_)___   _ __ | | ___  __ _ ___  ___ 
 | '__/ _ \ __/ _ \/ __| __| | __| '_ \| / __| | '_ \| |/ _ \/ _` / __|/ _ \
 | | |  __/ ||  __/\__ \ |_  | |_| | | | \__ \ | |_) | |  __/ (_| \__ \  __/
 |_|  \___|\__\___||___/\__|  \__|_| |_|_|___/ | .__/|_|\___|\__,_|___/\___|
                                               |_|                          
</pre>

**Comment by ljhljh235** [comment]
@azuresdkci retest this please

**Comment by devigned** [comment]
please do not use swagger bat. If you have acceptance tests, please just make them acceptance tests.

**Comment by ljhljh235** [comment]
@azuresdkci test this please

**Comment by ljhljh235** [comment]
@azuresdkci retest this please

**Comment by ljhljh235** [comment]
@azuresdkci @test this please

**Comment by ljhljh235** [comment]
@azuresdkci test this please

**Comment by devigned** [comment]
please update the pull request

**Pull request merged**
