### PR TITLE
Improve Python 3.5 reliability on Travis

### PR DESCRIPTION
**Pull request by lmazuel**
@olydis This should fix your Travis build. Might require Python 3.6 installation on Jenkins.

### CODE REVIEW

**Comment by lmazuel** [comment]
@olydis
- Python OK on Travis, failed because of missing `mvn` now.
- Python KO on Jenkins, because Python3.6 is not on Travis

I think I understand why Py3.5 stopped working on Travis, so if you prefer I can revert to use Py3.5 (this avoid you updating Jenkins to 3.6). But moving to 3.6 makes sense. Up to you!

**Comment by lmazuel** [comment]
@olydis I reverted to Py3.5. Moving to 3.6 in Jenkins should not be made in a hurry if not necessary.

**Comment by fearthecowboy** [comment]
I saw: 

image

So I have a PR that includes that. Maybe we can just use the old environment for a while longer :D

**Comment by fearthecowboy** [comment]
Closing for now.

**Pull request closed without merging**
