### PR TITLE
Proposal to handle error status codes

### PR DESCRIPTION
**Pull request by dsgouda**
Addressing issues
#2022, #2496, #1024, #1111, #855, #1523, #2341, #1654

### CODE REVIEW

**Comment by olydis** [comment]
# publish job
~~~ Haskell
> waiting for PR to get merged or closed
~~~

**Comment by olydis** [comment]
# AutoRest automatic publish job
~~~ Haskell
> will publish once/if PR gets merged
~~~

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by lmazuel** [comment]
Just to be sure, then it should be possible to use discriminator on the result right?
Like, I have several scenarios that returns a 400, BUT based on the `error_code` in the JSON, I want different classes to be thrown. Seems this proposal enables it as well. Thoughts?

**Comment by dsgouda** [comment]
@lmazuel yes that is exactly what we are trying to address here
Keep in mind the same model could theoretically be referenced by both successful and error return codes, which is why we need to disambiguate between the model names as `SomeModel` and `SomeModelException`. 
The modeler needs to be able to set the appropriate property on the model based on which operation returns it and I am planning to add that feature as step 0.

More comments welcome.

**Comment by dsgouda** [comment]
When it came to actual implementation, I ran into a couple of issues
- Setting the exception message before/after the deserialization of the error model, this is either non trivial (needs manipulation at the clientruntime level) or hacky since the underlying field is a readonly property, also we need to set this error message on the fly since error models could be shared between status codes
- Combining our polymorphism support with exceptions would be a complicated affair not to mention we will have to create an exception class of every model `allOfed`.
- An added complication would be evaluating all the `exception` classes we need to create when generating the code model.

An alternative solution could be:
Keep the `Body` property as is in the `RestException` class, inherit it in the desired subclass and write getter methods to return all the properties of the wrapped `Body` object, in the process we can even hide the body object altogether.
This means that we can still bubble up all the properties of the underlying model, leverage the existing polymorphism support for regular model classes, set custom messages for each exception and solve the issues listed above

The modified proposal is opened as a separate PR (here)[https://github.com/Azure/autorest/pull/2662]

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by dsgouda** [comment]
Closing in favor of an improved implementation [here](https://github.com/Azure/autorest/pull/2662)

**Pull request closed without merging**
