### PR TITLE
CSharp generator: Support uuid format as guid type

### PR DESCRIPTION
**Pull request by jhancock93**
Addresses issue #481 for CSharp generator.
type="string", format="uuid" schema elements in swagger will be treated as Guid in the CSharp generator.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@jhancock93__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by jhancock93** [comment]
I'm not sure I understand the problem with the CI build. Can any of the admins shed some light on the failure?

**Comment by amarzavery** [comment]
@azuresdkci - Test this please!

**Comment by amarzavery** [comment]
@jhancock93 - The test failed as there was no coverage scenario of nodeJS. The feature needs to be implemented in all the supported languages otherwise there will be a feature debt that is hard to maintain.

```
18:44:40 No coverage for scenario: getArrayUuidWithInvalidChars
18:44:40 
18:44:40 No coverage for scenario: putArrayUuidValid
18:44:40 
18:44:40 Passed: 481, Total: 484, coverage: 99% .
18:44:40 
  1) nodejs Swagger BAT coverage report should have 100% coverage
18:44:40 
18:44:40   238 passing (10s)
18:44:40   1 failing
18:44:40 
18:44:40   1) nodejs Swagger BAT coverage report should have 100% coverage:
18:44:40 
18:44:40       Uncaught AssertionError: expected 99 to be 100
18:44:40       + expected - actual
18:44:40 
18:44:40       -99
18:44:40       +100
18:44:40       
18:44:40       at D:\workspace\autorest\AutoRest\Generators\NodeJS\NodeJS.Tests\AcceptanceTests\coverageTest.js:39:33
18:44:40       at D:\workspace\autorest\AutoRest\Generators\NodeJS\NodeJS.Tests\Expected\AcceptanceTests\Report\autoRestReportService.js:174:12
18:44:40       at _stream_readable.js:908:16
18:44:40 
18:44:40 
18:44:40 
18:44:40 npm ERR! Test failed.  See above for more details.
18:44:40 [18:44:39] 'test:node' errored after 38 s
```

**Comment by jhancock93** [comment]
Given the merge conflicts, I'm closing this pull request and I will rebase the code on top of the latest and issue a new pull request once that is done.

**Pull request closed without merging**
