### PR TITLE
Fixing gulpfile to actually run CSharp generator tests

### PR DESCRIPTION
**Pull request by brjohnstmsft**
Also committing a few changes made to project.lock.json files when I ran the
build. Please let me know if I should revert those.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@brjohnstmsft__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (brjohnst). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by brjohnstmsft** [comment]
Not sure why the CI build failed. Looks like the test server returned 500 in one of the LRO tests. It worked fine in my local environment. Will try again in case it was transient.

**Comment by brjohnstmsft** [comment]
@azuresdkci retest this please

**Comment by stankovski** [comment]
@azuresdkci add to whitelist

**Comment by stankovski** [comment]
@brjohnstmsft can you pull from upstream and resolve conflicts?

**Comment by brjohnstmsft** [comment]
Will send a new PR

**Pull request closed without merging**
