### PR TITLE
Python updates

### PR DESCRIPTION
**Pull request by annatisch**
Fix for issue #1356 and #1300

### CODE REVIEW

**Comment by yugangw-msft** [comment]
this fixes Azure/azure-cli#754

**Comment by tbombach** [comment]
Looks good to me. Let me know if I should wait to merge if you want other Python eyes on this

**Comment by lmazuel** [comment]
I'm happy and my tests are ok! @tbombach for me you can merge. :)

**Comment by tbombach** [comment]
Merged

**Comment by yugangw-msft** [comment]
@tbombach thanks!
@annatisch @lmazuel , do we need to up the version, publish and let sdk-for-python to pick it up?

**Comment by lmazuel** [comment]
@yugangw-msft will be msrest/msrestazure 0.4.x versions, no need to republish the SDK for that. I plan to to do it today.

**Comment by yugangw-msft** [comment]
@lmazuel thanks!

**Comment by lmazuel** [comment]
@yugangw-msft Released, see https://github.com/Azure/autorest/pull/1398

**Pull request merged**
