### PR TITLE
Fix for #967: C# generator generates code that contains compiler warnings

### PR DESCRIPTION
**Pull request by kirthik**
cc @tbombach

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@kirthik__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (kirthik). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by tbombach** [comment]
@azuresdkci add to whitelist

**Comment by tbombach** [comment]
@azuresdkci - Test this please!

**Comment by tbombach** [comment]
@azuresdkci - Test this please!

**Comment by hovsepm** [comment]
@azuresdkci add to whitelist

**Pull request merged**
