### PR TITLE
Fixed resolving relative swaggers

### PR DESCRIPTION
**Pull request by amarzavery**

### CODE REVIEW

**Comment by amarzavery** [comment]
Fixes https://github.com/Azure/autorest/issues/1778. Have tested this locally

**Comment by lmazuel** [comment]
@amarzavery if you need my example, it's here:
https://github.com/Azure/azure-rest-api-specs-pr/tree/master/arm-datafactory/2015-10-01/swagger

**Comment by amarzavery** [comment]
Yup. I tested my fix on that spec and Autorest does not give an error. Please feel free to pull from [my fork](https://github.com/amarzavery/autorest/tree/fixresolve) and give it a try. This should definitely unblock you.

**Comment by lmazuel** [comment]
@amarzavery I confirm it's ok from your fork!!! Thanks :)

**Comment by amarzavery** [comment]
@lmazuel - Thank you. Sorry for messing it up the first time.

**Comment by olydis** [comment]
@amarzavery Note the changed folder structure (now uniform across all projects). Please move your added swagger files to the right spot (`Resource/...`) and CI should be happy :-)

**Comment by amarzavery** [comment]
Sure sir. will do that.

**Comment by olydis** [comment]
Thank you sir.

**Pull request merged**
