### PR TITLE
[Python] If LRO + Pageable, choose LRO

### PR DESCRIPTION
**Pull request by lmazuel**
Less of two evils, waiting for https://github.com/Azure/autorest/issues/2523

### CODE REVIEW

**Comment by lmazuel** [comment]
@olydis @fearthecowboy Jenkins failure seems unrelated to the change

**Comment by lmazuel** [comment]
And Travis is timeout, please tell me if I can do anything

**Comment by olydis** [comment]
@lmazuel will take this in once we finished splitting up the repo (no nightlies until then anyways) 🙂

**Comment by olydis** [comment]
moved to https://github.com/Azure/autorest.python/pull/2

**Pull request closed without merging**
