### PR TITLE
Fix the build for non-Windows and ensure it stays fixed

### PR DESCRIPTION
**Pull request by devigned**
## Why
Build has been broken for non-Windows for about a week

## things done
- fixed the csproj issues that cause Xamarin studio to show configuration issues
- build works in XS
- break out Win only projects into their own solution
- update gulp-msbuild, which had a bug related to xbuild /maxcpucount
- add travis-ci config so that build breakage in non-windows is exposed early
- move all test coordination to gulp

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@devigned__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (dajustic). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by devigned** [comment]
cortana retest please

**Comment by devigned** [comment]
retest this please

**Comment by markcowl** [comment]
@azuresdkci add to whitelist

**Pull request merged**
