### PR TITLE
Ported CSharp ClientRuntimes to CoreCLR RC2

### PR DESCRIPTION
**Pull request by hovsepm**

### CODE REVIEW

**Comment by hovsepm** [comment]
@azuresdkci retest this please

**Comment by hovsepm** [comment]
@azuresdkci retest this please

**Comment by hovsepm** [comment]
CI successfull: http://azuresdkci.cloudapp.net/view/3-AutoRest/job/autorest-netcore/26

**Comment by hovsepm** [comment]
CI successfull: http://azuresdkci.cloudapp.net/view/3-AutoRest/job/autorest-netcore/26 
Sign Successfull: http://azuresdkci.cloudapp.net/view/3-AutoRest/job/autorest-sign-netcore/3/

**Comment by hovsepm** [comment]
CI successfull: http://azuresdkci.cloudapp.net/view/3-AutoRest/job/autorest-netcore/26 
Sign Successfull: http://azuresdkci.cloudapp.net/view/3-AutoRest/job/autorest-sign-netcore/3/

**Comment by hovsepm** [comment]
CI successfull: http://azuresdkci.cloudapp.net/view/3-AutoRest/job/autorest-netcore/26 
Sign Successfull: http://azuresdkci.cloudapp.net/view/3-AutoRest/job/autorest-sign-netcore/3/

**Comment by hovsepm** [comment]
CI successful: http://azuresdkci.cloudapp.net/view/3-AutoRest/job/autorest-netcore/40/ 
Sign successful: http://azuresdkci.cloudapp.net/view/3-AutoRest/job/autorest-sign-netcore/4/

**Comment by hovsepm** [comment]
CI successful: http://azuresdkci.cloudapp.net/view/3-AutoRest/job/autorest-netcore/42/ 
Sign successful: http://azuresdkci.cloudapp.net/view/3-AutoRest/job/autorest-sign-netcore/4/

**Comment by hovsepm** [comment]
CI successful: http://azuresdkci.cloudapp.net/view/3-AutoRest/job/autorest-netcore/43/ 
Sign successful: http://azuresdkci.cloudapp.net/view/3-AutoRest/job/autorest-sign-netcore/4/

**Comment by hovsepm** [comment]
CI successful: http://azuresdkci.cloudapp.net/view/3-AutoRest/job/autorest-netcore/44/ 
Sign successful: http://azuresdkci.cloudapp.net/view/3-AutoRest/job/autorest-sign-netcore/4/

**Comment by hovsepm** [comment]
CI successful: http://azuresdkci.cloudapp.net/view/3-AutoRest/job/autorest-netcore/45/ 
Sign successful: http://azuresdkci.cloudapp.net/view/3-AutoRest/job/autorest-sign-netcore/5/

**Comment by hovsepm** [comment]
@azuresdkci retest this please

**Comment by fearthecowboy** [comment]
Looks good to me.

**Comment by hovsepm** [comment]
green nightly: http://azuresdkci.cloudapp.net/view/3-AutoRest/job/autorest-nightly/365/ 
green sign: http://azuresdkci.cloudapp.net/view/3-AutoRest/job/autorest-sign/139/

**Comment by hovsepm** [comment]
Changed target branch from netcore to master in #1084

**Pull request closed without merging**
