### PR TITLE
Added support for PrimaryType.Buffer, mapping to "Buffer" type

### PR DESCRIPTION
**Pull request by BretJohnson**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@BretJohnson__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by matthchr** [comment]
Can you also run gulp regenerate:expected and commit all the files which are created by that?  Otherwise whoever runs that command next will end up having to include those files in their PR.

**Comment by amarzavery** [comment]
@BretJohnson - That makes perfect sense. Please execute 
```
gulp regenerate:expected:node
``` 
and include the generated files in this PR.

**Comment by BretJohnson** [comment]
Done - I added the regenerate:expected d.ts files to the pull request.

**Pull request merged**
