### PR TITLE
fix cross referencing models in relative swagger specs

### PR DESCRIPTION
**Pull request by amarzavery**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@amarzavery__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (amzavery). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by amarzavery** [comment]
@olydis - Please review.

**Comment by amarzavery** [comment]
https://github.com/Azure/azure-rest-api-specs/pull/913
https://github.com/Azure/autorest/issues/1778

**Comment by amarzavery** [comment]
should travis ci be ignored for now. I saw couple of other PRs failing in travis ci.

**Pull request merged**
