### PR TITLE
Add DateTime-Rfc1123 support to AutoRest

### PR DESCRIPTION
**Pull request by matthchr**
- Added header, body, dictionary, array,
   and complex body tests for C#, NodeJS, Java,
   and Ruby.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@matthchr__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (matthchr). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by matthchr** [comment]
Will check up on why travis has failed

**Comment by jianghaolu** [comment]
Looks like there is merge conflict, most probably caused by https://github.com/Azure/autorest/pull/392. Please resolve. (Most conflicts are probably in the generated files, which only need a regeneration to resolve.)

**Comment by matthchr** [comment]
Yes, I will resolve this merge conflict

**Pull request merged**
